name: "Just a Gwai Lo: Questions"
url: http://questions.justagwailo.com
description: "Questions asked on Twitter and elsewhere, sometimes with answers."
markdown: rdiscount
permalink: /:year/:month/:day/:title
gems:
  - jekyll-sitemap
rdiscount:
  extensions: [smart]
exclude:
  - "node_modules"